apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "calibre-web.fullname" . }}
  labels:
    app: {{ template "calibre-web.name" . }}
    chart: {{ template "calibre-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "calibre-web.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "calibre-web.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: get-or-update
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: init
              mountPath: /init/launch.sh # no launch
              subPath: no_launch.sh
{{ toYaml .Values.volumeMounts | indent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: init
              mountPath: /init/get_or_update.sh # no get or update
              subPath: no_get_or_update.sh
{{ toYaml .Values.volumeMounts | indent 12 }}
      volumes:
        - name: init
          configMap:
            name: {{ template "calibre-web.fullname" . }}
            items:
            - key: no_get_or_update.sh
              path: no_get_or_update.sh
              mode: 0755
            - key: no_launch.sh
              path: no_launch.sh
              mode: 0755
{{ toYaml .Values.volumes | indent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
